[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

via_ir = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
blast_sepolia = "${BLAST_SEPOLIA_RPC}"
mantle_sepolia = "${MANTLE_SEPOLIA_RPC}"
bsc_testnet = "${BSC_TESTNET_RPC}"
bsc_mainnet = "${BSC_MAINNET_RPC}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = "84532", url = "${BASESCAN_API_URL}" }
blast_sepolia = { key = "${BLASTSCAN_API_KEY}", chain = "168587773", url = "${BLASTSCAN_API_URL}" }
mantle_sepolia = { key = "${MANTLESCAN_API_KEY}", chain = "5003", url = "${MANTLESCAN_API_URL}" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = "97", url = "${BSCSCAN_TESTNET_API_URL}" }
bsc_mainnet = { key = "${BSCSCAN_API_KEY}", chain = "56", url = "${BSCSCAN_API_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
